name: pensionate

networks:
  streamlitdocker_pensionate:
    name: streamlitdocker_pensionate
    driver: bridge

services:
  streamlit:
    image: "streamlit/pensionate:${DATE:-latest}"
    container_name: streamlit_pensionate
    hostname: streamlit_pensionate
    pull_policy: never
    tty: true
    ports:
      - "8502:8502"
    build:
      context: ..
      dockerfile: docker/streamlit_pensionate/streamlit_pensionate.df
    networks:
      - streamlitdocker_pensionate
    volumes:
      - "../:/app"
    healthcheck:
      test: ["CMD", "ps", "aux", "|","grep","streamlit"]
      timeout: 10s
      retries: 10

